src/burn/drv/capcom/d_cps1.cpp

CPS1: sf2mix 1.0

---

src/burn/drv/capcom/d_cps2.cpp

Added spf2xpri.
spf2tcb, new version.

CPS2: Updates

---

src/burn/drv/cps3/d_cps3.cpp

Additional inputs needed to be added for jojobanrc since it uses "Not in Use 1"
Alessi/Child Mode: https://archive.org/details/jojobanch
Roman Cancel: https://archive.org/details/jojobanrc
Alessi/Child Mode Lobby Image: https://cdn.discordapp.com/attachments/710768934055575662/890987377105965126/jojobanr1-09-23-194454.png
Roman Cancel Lobby Image: https://media.discordapp.net/attachments/710768934055575662/890987415613886524/jojobanr1-09-23-195904.png

Added jojobanch (Alessi/Child Mode) and jojobanrc (Roman Cancel)

---

src/burn/drv/capcom/d_cps2.cpp

Add cyberbots hack

---

src/burner/luaengine.cpp
src/cpu/m68000_intf.cpp
src/cpu/m68k/m68kcpu.c

Let's see if dink has any caveats before merge. Edit: They are merged into FBNeo. 
Edit: Have tested. Fixed build by commenting out `extern int rollbackframes` and the `audwasapi` drivers.

Merge lua fixes

---

src/burn/drv/cps3/cps3run.cpp
src/burn/drv/sms/d_sms.cpp

sfiii3ws doesn't need to be resized at all 
also, added sms_alexkidd3f

Sfiii3ws fix

---

src/burn/drv/neogeo/d_neogeo.cpp

already added in fc2 as kof2k1rp

d_neogeo: removed kof2001rpf

---

src/burn/drv/neogeo/d_neogeo.cpp

d_neogeo: kof97evn

---

src/burn/drv/nes/d_nes.cpp

Added 2p version with "next on top"

d_nes: add tetristpn

---

src/burn/drv/capcom/d_cps2.cpp
src/burn/drv/megadrive/d_megadrive.cpp

d_megadrive: fightvengt

---

src/burn/drv/capcom/d_cps2.cpp
src/burn/drv/megadrive/d_megadrive.cpp

latest version. P2 metalo special fix
Also, correct release year for ssf2tnl

d_megadrive: fightvengt 3.0

---

src/burn/drv/capcom/d_cps1.cpp
src/burn/drv/neogeo/d_neogeo.cpp

d_neogeo: kof98bc2k2

---

src/burn/drv/neogeo/d_neogeo.cpp

Version as on HBMAME with proper labels

d_neogeo: fatfurspbs

---

src/burn/drv/neogeo/d_neogeo.cpp

d_neogeo: mslug3sc

---

src/burn/drv/megadrive/d_megadrive.cpp
src/burn/drv/neogeo/d_neogeo.cpp
src/burn/drv/nes/d_nes.cpp

Updated to latest version.
Also, d_nes: typo / d_megadrive: add insanepain

d_neogeo: mslugxsc

---

src/burner/gami.cpp

changed the behaviour of the "hitbox-style" SOCD cleaner to behave like the socd cleaner in the original hardware

changed behaviour of "hitbox-style" SOCD cleaner

---

src/burn/drv/neogeo/d_neogeo.cpp

Name changes in some metal slug hacks (Alicemu request)

d_neogeo: ms hacks - name changes

---

src/burn/drv/megadrive/d_megadrive.cpp

d_megadrive: sor2 hack

---

src/burn/drv/irem/d_m92.cpp
src/burn/drv/megadrive/megadrive.cpp
src/burn/drv/neogeo/d_neogeo.cpp
src/burn/drv/pst90s/d_ddragon3.cpp

Online dipsw
-ctribe
-hook
-uccopsar
-issdx hacks
d_neogeo
-Add mslug5f
-mslugxsc updated to latest version

new online dipsw

---

src/burn/drv/neogeo/d_neogeo.cpp

d_neogeo update: 2 new kof98 hacks

---

src/burn/drv/capcom/d_cps2.cpp
src/burn/drv/neogeo/d_neogeo.cpp

cps2 added sfa3fp
neogeo added kof2002sc

d_cps2 update: new sfa3 hack

---

src/burn/drv/neogeo/d_neogeo.cpp

d_neogeo update: extra kof2002 hack
